# Generated by Django 4.0.5 on 2022-07-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(choices=[('1', '1. grade'), ('2', '2. grade'), ('3', '3. grade'), ('4', '4. grade')], null=True),
        ),
    ]
