# Generated by Django 4.0.5 on 2022-07-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='lettergrade',
            field=models.CharField(choices=[('AA', 'AA'), ('BA', 'BA'), ('BB', 'BB'), ('CB', 'CB'), ('CC', 'CC'), ('DC', 'DC'), ('DD', 'DD'), ('FD', 'FD'), ('FF', 'FF')], max_length=2, null=True),
        ),
    ]
