# Generated by Django 3.0.5 on 2022-07-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20220727_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(choices=[('sinif1guz', '1. Sınıf Güz'), ('sinif1bahar', '1. Sınıf Bahar'), ('sinif2guz', '2. Sınıf Güz'), ('sinif2bahar', '2. Sınıf Bahar'), ('sinif3guz', '3. Sınıf Güz'), ('sinif3bahar', '3. Sınıf Bahar'), ('sinif4guz', '4. Sınıf Güz'), ('sinif4bahar', '4. Sınıf Bahar')], max_length=20, null=True),
        ),
    ]
