# Generated by Django 3.0.5 on 2022-07-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20220729_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='ort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('gecti', 'Geçti'), ('kaldi', 'Kaldı')], max_length=5, null=True),
        ),
    ]
