# Generated by Django 3.2.14 on 2022-07-31 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20220731_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student',
            field=models.ManyToManyField(to='myapp.Student'),
        ),
    ]
