# Generated by Django 3.2.14 on 2022-07-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_lesson_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(choices=[('1. Sınıf Güz', '1. Sınıf Güz'), ('1. Sınıf Bahar', '1. Sınıf Bahar'), ('2. Sınıf Güz', '2. Sınıf Güz'), ('2. Sınıf Bahar', '2. Sınıf Bahar'), ('3. Sınıf Güz', '3. Sınıf Güz'), ('3. Sınıf Bahar', '3. Sınıf Bahar'), ('4. Sınıf Güz', '4. Sınıf Güz'), ('4. Sınıf Bahar', '4. Sınıf Bahar')], max_length=20, null=True),
        ),
    ]
