# Generated by Django 3.2.14 on 2022-08-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_period_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='period',
        ),
        migrations.AddField(
            model_name='period',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.lesson'),
        ),
    ]
