# Generated by Django 3.2.14 on 2022-08-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20220801_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='lesson',
        ),
        migrations.AddField(
            model_name='period',
            name='lesson',
            field=models.ManyToManyField(to='myapp.Lesson'),
        ),
    ]
